# Generated by Django 3.2.4 on 2021-07-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0003_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='patient_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='patient_last_name',
            new_name='last_name',
        ),
    ]
