# Generated by Django 3.2.4 on 2021-07-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0005_auto_20210701_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultations',
            old_name='patient_last_name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='consultations',
            name='doctor_last_name',
        ),
    ]
