# Generated by Django 3.2.4 on 2021-07-01 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0007_auto_20210701_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultations',
            name='consultation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
